name: CI for FizzBuzz World

on:
  push:
    branches:
      - main   # Run the tests when code is pushed to the main branch
  pull_request:
    branches:
      - main   # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23 # Specify your Go version

    - name: Install dependencies
      run: |
        go mod download

    - name: Run tests with make
      run: |
        make test
